# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift'
    version: '4.2'
    cmd: 'start build <BUSCAR NOMBRE> --follow'
  displayName: 'Start build'
  
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift'
    version: '4.2'
    cmd: 'oc status'
  displayName: 'Check status'

- script: |
    npm install
#    npm run build
  displayName: 'npm install'
